// Code generated by protoc-gen-go.
// source: log.proto
// DO NOT EDIT!

package log

import proto "code.google.com/p/goprotobuf/proto"
import json "encoding/json"
import math "math"

// Reference proto, json, and math imports to suppress error if they are not otherwise used.
var _ = proto.Marshal
var _ = &json.SyntaxError{}
var _ = math.Inf

type LogEvent struct {
	Source           *string  `protobuf:"bytes,1,req,name=source" json:"source,omitempty"`
	Timestamp        *string  `protobuf:"bytes,2,req,name=timestamp" json:"timestamp,omitempty"`
	Tags             []string `protobuf:"bytes,5,rep,name=tags" json:"tags,omitempty"`
	Message          *string  `protobuf:"bytes,8,req,name=message" json:"message,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *LogEvent) Reset()         { *m = LogEvent{} }
func (m *LogEvent) String() string { return proto.CompactTextString(m) }
func (*LogEvent) ProtoMessage()    {}

func (m *LogEvent) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

func (m *LogEvent) GetTimestamp() string {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return ""
}

func (m *LogEvent) GetTags() []string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *LogEvent) GetMessage() string {
	if m != nil && m.Message != nil {
		return *m.Message
	}
	return ""
}

func init() {
}
